version: "3.8"

services:
  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REPO_DOWNLOADER_ENABLED: ${REPO_DOWNLOADER_ENABLED}
        WATCHMAN: "true"
      network: host
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl
      - ../custom_ruleset:/opt/deploy/yara/custom_ruleset
    environment:
      - DEBUG=True
      - DJANGO_TEST_SERVER=True
      - DJANGO_WATCHMAN_TIMEOUT=20

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile_nginx
    image: intelowlproject/intelowl_nginx:test
    volumes:
      - ../configuration/nginx/django_server.conf:/etc/nginx/conf.d/default.conf

  celery_beat:
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl
      - ../custom_ruleset:/opt/deploy/yara/custom_ruleset

  celery_worker_default:
    image: intelowlproject/intelowl:test
    dns:
      - 8.8.8.8
    volumes:
      - ../:/opt/deploy/intel_owl
      - ../custom_ruleset:/opt/deploy/yara/custom_ruleset
